### PR TITLE
HPE Comware support

### PR DESCRIPTION
**Pull request by murrant**
Initial HPE Comware support.

It isn't exactly clear what the difference between cli, operation, and config are.

I looked at the other device models and they are inconsistent.  Some disconnect at the end and others do not.
Clarification would be great.

### CODE REVIEW

**Comment by epiecs** [comment]
Hi,

- I should make things more consistent soon :). 

- Where do you have questions regarding the disconnects so I can have a look at them.

- I should document the cli/operation and config better. But it works like this:

Cisco: cli is user exec, operation is privileged exec (enable mode) and configure are configuration commands

Juniper: cli is the bare linux shell, operation is junioer cli mode (cli command) and config is the configuration mode

Looking at page 12 of this [guide](https://www.catelsys.eu/images/Catelsys/images/2017/04/0-Notices-HPE_Aruba_and_Cisco_CLI_Ref_Guide.pdf#page13)

hpe comware: cli is user exec, operation is also cli and config would be system-view.

the approach i took has some issues with devices that have two privilege tiers when you want to make it consistent :(

**Comment by murrant** [comment]
In Cisco_ios, both operation() and configure() disconnect the ssh session after running the command.  cli() does not.

I have a guess that disconnect is supposed to be exit to return to unprivileged...

**Comment by epiecs** [comment]
Ill have to look into that. Nice find. I should review the entire codebase to make it more consistent.

**Comment by epiecs** [comment]
Hi,

I checked and cleaned up the code base and updated the docs. Thanks for this contribution!

**Pull request merged**
